services:
  mongodb:
    image: mongo:7
    container_name: zoterosci-stats-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: zoterosci-stats

volumes:
  mongo-data:
